[package]
name = "nitrogql-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
colored = "3.0.0"
nitrogql-ast = { path = "../ast" }
nitrogql-utils = { path = "../utils" }
